CREATE TABLE IF NOT EXISTS points (
	id INTEGER PRIMARY KEY,
	X REAL NOT NULL,
	Y REAL NOT NULL,
	Z REAL NOT NULL,
	r INTEGER,
    g INTEGER,
	b INTEGER,
	scan_id INTEGER
);

CREATE TABLE IF NOT EXISTS scans (
	id INTEGER PRIMARY KEY,
	name TEXT NOT NULL,
	LEN INTEGER,
	X_min REAL,
	X_max REAL,
	Y_min REAL,
	Y_max REAL,
	Z_min REAL,
	Z_max REAL
);

DROP TABLE points;

CREATE TABLE IF NOT EXISTS points (
	id INTEGER PRIMARY KEY,
	X REAL NOT NULL,
	Y REAL NOT NULL,
	Z REAL NOT NULL,
	r INTEGER,
    g INTEGER,
	b INTEGER,
	scan_id INTEGER,
	FOREIGN KEY (scan_id) REFERENCES scans (id) ON DELETE CASCADE ON UPDATE CASCADE
);